name: machine
description: "First CRUD using Flutter and Dart"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.4.0
  provider: ^6.1.5
  dio: ^5.8.0+1
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/svg/edit.svg
    - assets/svg/getApiData.svg
    - assets/svg/yofunding.svg

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
